name: landmarks
description: A Flutter implementation of the SwiftUI main tutorial
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  apple_maps_flutter: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  assets:
   - assets/